#!/usr/bin/env python3
"""
Plot wheel-physics diagnostics generated by SimRobot.

Usage:
    python plot_wheel_physics.py wheel_physics_robot_0.csv
"""

import csv
import sys
from pathlib import Path

import matplotlib.pyplot as plt


def read_csv(path):
    with open(path, newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise RuntimeError("CSV contains no samples")

    def col(name):
        return [float(row[name]) for row in rows]

    return col


def plot(path):
    col = read_csv(path)
    out_dir = Path(path).with_suffix("")
    out_dir.mkdir(exist_ok=True)

    time = col("time")

    fig, ax = plt.subplots()
    ax.plot(time, col("robot_vx"), label="vx")
    ax.plot(time, col("robot_vy"), label="vy")
    ax.plot(time, col("robot_omega"), label="omega")
    ax.set_xlabel("Time [s]")
    ax.set_ylabel("Velocity")
    ax.legend()
    ax.grid(True)
    fig.tight_layout()
    fig.savefig(out_dir / "01_robot_velocity.png", dpi=150)
    plt.close(fig)

    fig, ax = plt.subplots()
    ax.plot(time, col("total_fx"), label="Fx")
    ax.plot(time, col("total_fy"), label="Fy")
    ax.plot(time, col("total_tz"), label="Tz")
    ax.set_xlabel("Time [s]")
    ax.set_ylabel("Force / torque")
    ax.legend()
    ax.grid(True)
    fig.tight_layout()
    fig.savefig(out_dir / "02_total_wrench.png", dpi=150)
    plt.close(fig)

    for wheel in range(4):
        fig, ax = plt.subplots()
        ax.plot(time, col(f"w{wheel}_transverse_slip"))
        ax.set_xlabel("Time [s]")
        ax.set_ylabel("Transverse slip [m/s]")
        ax.set_title(f"Wheel {wheel} transverse slip")
        ax.grid(True)
        fig.tight_layout()
        fig.savefig(out_dir / f"wheel_{wheel}_slip.png", dpi=150)
        plt.close(fig)

        fig, ax = plt.subplots()
        ax.plot(time, col(f"w{wheel}_transverse_force"))
        ax.set_xlabel("Time [s]")
        ax.set_ylabel("Transverse force [N]")
        ax.set_title(f"Wheel {wheel} transverse force")
        ax.grid(True)
        fig.tight_layout()
        fig.savefig(out_dir / f"wheel_{wheel}_force.png", dpi=150)
        plt.close(fig)

        fig, ax = plt.subplots()
        ax.plot(time, col(f"w{wheel}_phase_rad"))
        ax.set_xlabel("Time [s]")
        ax.set_ylabel("Roller phase [rad]")
        ax.set_title(f"Wheel {wheel} roller phase")
        ax.grid(True)
        fig.tight_layout()
        fig.savefig(out_dir / f"wheel_{wheel}_phase.png", dpi=150)
        plt.close(fig)

    print(f"Wrote plots to {out_dir}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("Usage: python plot_wheel_physics.py wheel_physics_robot_N.csv")
    plot(sys.argv[1])
